table pbi_dim_segment
	lineageTag: ccaf7e33-f84f-4f05-bc67-c1ce90517673

	column segment
		dataType: string
		lineageTag: 03b0093b-3ade-457c-a632-66c8b189fdeb
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column segment_en
		dataType: string
		lineageTag: 92546969-0729-460b-b5e4-1052f397beb5
		summarizeBy: none
		sourceColumn: segment_en

		annotation SummarizationSetBy = Automatic

	column sort
		dataType: int64
		formatString: 0
		lineageTag: 48316c34-4d2c-4afe-9e58-ab7ed0d641ab
		summarizeBy: sum
		sourceColumn: sort

		annotation SummarizationSetBy = Automatic

	column definition
		dataType: string
		lineageTag: 1bbe5862-e176-4f26-a11b-35f55e43b5e9
		summarizeBy: none
		sourceColumn: definition

		annotation SummarizationSetBy = Automatic

	column action
		dataType: string
		lineageTag: 1ee2f460-5c2c-49df-9b53-8ce27a0a908a
		summarizeBy: none
		sourceColumn: action

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: string
		lineageTag: 3ea0c444-4668-4838-b0c4-4fc8141005a7
		summarizeBy: none
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	partition pbi_dim_segment = m
		mode: import
		source =
				let
				  源 = Csv.Document(File.Contents("C:\olist_powerbi_data\pbi_dim_segment.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  已提升标题 = Table.PromoteHeaders(源, [PromoteAllScalars = true]),
				  已更改列类型 = Table.TransformColumnTypes(已提升标题, {{"segment", type text}, {"segment_en", type text}, {"sort", Int64.Type}, {"definition", type text}, {"action", type text}, {"priority", type text}}, "zh-Hans")
				in
				  已更改列类型

	annotation PBI_ResultType = Table

